### ISSUE TITLE
conda-forge license violation

### ISSUE THREAD

**Issue by isuruf** [unlhcc/hcc-conda-recipes#12]
It was brought to my attention that some of the recipes like octave recipe is a copy from conda-forge with some modifications.

If so, you have to distribute the license along with the copyright notice that conda-forge adds to the recipes.
For eg: https://github.com/conda-forge/octave-feedstock/blob/master/LICENSE.txt

**Comment by isuruf** [comment]
cc @npavlovikj

**Comment by npavlovikj** [comment]
@isuruf , thank you for letting us know about the violation, we were not aware of the separate feedstock licensing. We changed the license of our repo to BSD-3, which is more permissive. I hope that solves the issue, and please let us know if you have any other concerns.

**Comment by isuruf** [comment]
Thanks @npavlovikj. Thanks for making the license permissive even though the only requirement is that you copy conda-forge's license in addition to yours. In order to make if fully compliant, can you add conda-forge's copyright below yours at https://github.com/unlhcc/hcc-conda-recipes/blob/master/LICENSE#L3 ?

```
BSD 3-Clause License

Copyright (c) 2022, Holland Computing Center
Copyright (c) 2015-2022, conda-forge contributors
All rights reserved.
```

**Comment by npavlovikj** [comment]
Done :)  We don't have feedstocks as CF does, and we have recipes that are CF/Bioconda independent, so I think this is cleaner solution. Thank you again for letting us know!

**Comment by isuruf** [comment]
Thanks @npavlovikj
